[package]
name = "www"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bip322 = "0.0.7"
bitcoin = "0.32.3"
wasm-bindgen = "0.2.92"

[patch.crates-io]
bip322 = { path = '../' }
